language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - TWINE_USERNAME=pauldmccarthy
    - secure: "tc7qlO6QZkQSBHur0gPDyd+CxK3Km36WMXz7Hbe8BJTu0aucJm3WN5fy2aq6dty9V3wIxdjCArw7XDmsOf9Oy/coHl/uD/AFN7sdxlU8+fcqwY0h5wB4xlSrXQy5QEbzCCHbL+REHUnzEsellv4vJhS7EgeUeid1wq74JjLKv1ys1xxqawNkTY1G9TVelPIhUfuwrxzLsXwhZTdNCtG6Ba1C5wVxiELCnC8oS7VuX0R7EhUZ1knt3UwTitFfdSG/4gdlTr7gfc47zXMN3ViJmHJCp2hWx3zchiuhT68szGTcFYpSuZLVgKOQghtKiVK4tvn7zUmHRozMY6lRObXfZzVK+bRKdELOYahvsv1OcHpJ7LQ3XUv4kBeh4H8FXPANOXw1PHMhsxVJluQPxI6JNrZj/n/OG9WzS6p8RII6tQjyeeXLk/gZfGZ3kZNqltYjH4fw76JGrmeSUHdM/4AVs46GsyIyLh0w/0ENxDeMJ3P3e7jfD2ybNP/Dv/mrIwQNFyZ12aiXGXDLjENbPfziX6AtTwTvAHivBJ1zryO+uOD2AjjS4CP9SBeOtJHaO6VUYYQAUVn2txjJb1kgC/unzcnNOaegVWumfRKgfChuTT7mmjEJYbMyvMpbjovCytVU/uXBxoJLlC4UM9dfmIvpv3/XVUCVD7zaMUtyI7RnBvU="


script:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
  - if [ `python setup.py -V` != "$TRAVIS_TAG"]; then echo "Error - tag does not match version"; exit 1; fi
  - pip install twine
  - python setup.py sdist
  - twine upload dist/*
