language: python

python:
  - "3.6"

services:
  - docker

deploy:
  provider: pypi
  username: pauldmccarthy
  password:
    secure: "QJGbB1YehsWaa/NpaNd6xfxsGr6QvpxuGBe7KpQytsX/tRLkXA1oaYjEZ5A/+0yIn+MbLWlfZ8SaPhx3uP/kMsZ4vO6xexRTt8bZ23gN8wlxoznh1wpG0dNUmVQbkp+LNGRSaQstrc8EiStWc2JQSoHzDaWL59AhPn7M/1QrrxU6Blrzxm7Q/cKaj8QmL9xd0XxeHH7js6AH94LJf+PvTnooBJO3VurhJ8qz11WCLjH46KK+s3ySJgua4IjFU9QjHozfo0Jp0/jZ3dUVh2fRHqFNIOlkUaCcst/n135dMV7r/l6SISe+USdLdjKC7hkmrB3bPSvQ833LKc8tSRhygKC/IEuO6NcukeD3LnPF37Wz/zunmoVp7vaJGm5iUkAO+Y+oGD6LxVUXsWF8Z6e+BIV+mO0I2FLQ9R5AMtoGe5Fs/wMiAlNAjFBeFkQToy6u2702K8HcFRHwcqSsIq60QH+rW/yzxGYS9Bje65ktvNR/FoidCdi0I26bC2FZ/8BkcqYxfo6oZC0/EC/I/q8dH8g/E5/ydNkoKKMv0zVtjInREYZ9mtU2lbls7XdmEj1muGtE2a3/QG2etwBeNy1fzpB1ha7g2W+RjeazW+viintd7TtzzGWQsFJOCtzLkxhcYDqJd8at21+S9F/zmo3/Nvi1S48oydhy59NYGagD0T8="
  on:
    tags: true

install:
  - echo "Overriding travis";

script:
  - echo "Building version $TRAVIS_TAG ...";
  - if [ -z "$TRAVIS_TAG" ]; then exit 0; fi
  - if [ `python setup.py -V` != "$TRAVIS_TAG" ]; then echo "Error - tag does not match version"; exit 1; fi
